
pipeline {
    agent any
    stages {
        stage ('Clone') {
            steps {
                git branch: 'master', url: "<GIT_URL>"
            }
        }

        stage ('Artifactory configuration') {
            steps {
                rtGradleDeployer (
                    id: "GRADLE_DEPLOYER",
                    serverId: "JFROG_INSTANCE",
                    repo: "<ARTIFACTORY_REPOSITORY>",
                )

                rtGradleResolver (
                    id: "GRADLE_RESOLVER",
                    serverId: "JFROG_INSTANCE",
                    repo: "<ARTIFACTORY_REPOSITORY>",
                )
            }
        }

        stage ('Exec Gradle') {
            steps {
                rtGradleRun (
                    // Tool name from Jenkins configuration
                    tool: "GRADLE_TOOL",
                    buildFile: 'build.gradle',
                    tasks: 'artifactoryPublish',
                    deployerId: "GRADLE_DEPLOYER",
                    resolverId: "GRADLE_RESOLVER",
                )
            }
        }

        stage ('Publish build info') {
            steps {
                rtPublishBuildInfo (
                    serverId: "JFROG_INSTANCE"
                )
            }
        }
    }
}
