node {
    def server = Artifactory.server 'JFROG_INSTANCE'
    def rtGo = Artifactory.newGoBuild()
    def buildInfo

    stage ('Clone') {
        git url: '<GIT_URL>'
    }

    stage ('Artifactory configuration') {
        rtGo.deployer repo: '<ARTIFACTORY_REPOSITORY>', server: server
        rtGo.resolver repo: '<ARTIFACTORY_REPOSITORY>', server: server
        buildInfo = Artifactory.newBuildInfo()
    }

    stage ('Go run') {
        rtGo.run buildInfo: buildInfo, args: 'build'
    }

    stage ('Go publish') {
        rtGo.publish buildInfo: buildInfo, version: '1.0.0'
    }

    stage ('Publish build info') {
        server.publishBuildInfo buildInfo
    }
}